### ISSUE TITLE
Freeze after create new project. JACK issue? Limited to only open files?

### ISSUE THREAD

**Issue by 38github** [OpenMandrivaAssociation/ardour#1]
$ ardour5 
bind txt domain [gtk2_ardour5] to /usr/share/ardour5/locale
Ardour5.9.0 (built using 5.9 and GCC version 6.3.1 20170206 (OpenMandriva))
ardour: [INFO]: Your system is configured to limit Ardour to only  open files
ardour: [INFO]: Loading system configuration file /etc/ardour5/system_config
ardour: [INFO]: Loading user configuration file /home/sef/.config/ardour/config
ardour: [INFO]: CPU vendor: GenuineIntel
ardour: [INFO]: AVX-capable processor
ardour: [INFO]: CPU brand:        Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
ardour: [INFO]: Using SSE optimized routines
ardour: [INFO]: Loading default ui configuration file /etc/ardour5/default_ui_config

(ardour-5.9.0:7806): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(ardour-5.9.0:7806): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Color shuttle bg not found
ardour: [INFO]: Loading color file /usr/share/ardour5/themes/dark-ardour.colors

(ardour-5.9.0:7806): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(ardour-5.9.0:7806): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
ardour: [INFO]: Loading ui configuration file /etc/ardour5/clearlooks.rc
Color : background not found
Color : text not found
Color : edited text not found
Color : cursor not found
Color : background not found
Color : text not found
Color : edited text not found
Color : cursor not found
Color : background not found
Color : text not found
Color : edited text not found
Color : cursor not found
ardour: [INFO]: Loading ui configuration file /etc/ardour5/clearlooks.rc
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Found nothing along /home/sef/.config/ardour/templates:/usr/share/ardour5/templates
run dialog
pingback: No Error
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JACK command line will be: /usr/bin/jackd -t 200 -p 2048 -R -T -d alsa -n 2 -r 44100 -p 1024 -d hw:PCH,0 -X raw
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:PCH,0|hw:PCH,0|1024|2|44100|0|0|nomon|swmeter|-|32bit
configuring for 44100Hz, period = 1024 frames (23.2 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
protocol Steinberg CC121 active ? 0
protocol PreSonus FaderPort active ? 0
protocol PreSonus FaderPort8 active ? 0
protocol Generic MIDI active ? 0
protocol Mackie active ? 0
protocol Open Sound Control (OSC) active ? 0
protocol Ableton Push 2 active ? 0
protocol Wiimote active ? 0
Scanning folders for bundled LV2s: /usr/lib64/ardour5/LV2
KP is ardour.keys
Set cursor set to default
JackEngine::XRun: client = ardour was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = ardour was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = ardour was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
JackEngine::XRun: client = ardour was not finished, state = Triggered
JackAudioDriver::ProcessGraphAsyncMaster: Process error
Segmentation fault (core dumped)
[sef@openmandriva ~]$ Unknown error...
terminate called after throwing an instance of 'Jack::JackTemporaryException'
  what():

**Comment by 38github** [comment]
Any news if the problem causing this is identified? Regards.

**Comment by AngryPenguinPL** [comment]
V 5.9 is no more in OMV. Current 6.7.0 should works fine.
